CONFIG_DISPLAY=y
CONFIG_INPUT=y
CONFIG_VIDEO=y
CONFIG_VIDEO_BUFFER_POOL_SZ_MAX=115200
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=2
CONFIG_VIDEO_BUFFER_POOL_ALIGN=32
CONFIG_VIDEO_BUFFER_USE_SHARED_MULTI_HEAP=y
CONFIG_VIDEO_BUFFER_SMH_ATTRIBUTE=2
CONFIG_DMA_ESP32_MAX_DESCRIPTOR_NUM=64
CONFIG_ESP_SPIRAM=y
CONFIG_SPIRAM_MODE_OCT=y

CONFIG_LVGL=y
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_LV_Z_VDB_SIZE=10
CONFIG_LV_USE_BAR=y
CONFIG_LV_USE_LABEL=y

CONFIG_CCSDS=y
CONFIG_CCSDS_CFDP=y
CONFIG_CCSDS_FRAME_SUPPORT=n
CONFIG_CCSDS_ROUTER_MAX_APIDS=4
CONFIG_CCSDS_CFDP_MAX_PDU_SIZE=512
CONFIG_CCSDS_CFDP_MAX_SEGMENT_SIZE=256
CONFIG_CCSDS_UDP_MAX_UNIT_LEN=1024
CONFIG_CCSDS_UDP_THREAD_STACK_SIZE=3072

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=y
CONFIG_NET_TCP=n
CONFIG_NET_SOCKETS=y
CONFIG_NET_DHCPV4=n
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_WIFI_USAGE_MODE_STA=y
CONFIG_ESP32_WIFI_STA_AUTO_DHCPV4=n
CONFIG_ESP32_WIFI_STA_RECONNECT=y
CONFIG_NET_MGMT=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_MAIN_STACK_SIZE=6144
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
